id: I550969E9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T08:25:04+00:00'
last_modified: '2022-06-07T14:55:32.358624+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18279
  title: དྲི་བ་དབྱུག་གུས་བསྣུན་པར་རྔ་རྒན་ཧྲིལ་པོའི་སྒྲ་དབྱངས་བློ་གསལ་རྣ་རྒྱན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C490:
      image_group_id: I8LS18300
      title: ''
      total_pages: 54
      order: 1
      base_file: C490.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
