id: I550969E9
legacy_id: P001749
ocr_import_info:
  bdrc_scan_id: W8LS18279
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T08:24:40'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T04:07:53.059778+00:00'
last_modified: 2022-09-04 12:07:58.127489
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W8LS18279
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW8LS18279
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དྲི་བ་དབྱུག་གུས་བསྣུན་པར་རྔ་རྒན་ཧྲིལ་པོའི་སྒྲ་དབྱངས་བློ་གསལ་རྣ་རྒྱན།
  author: རྡོ་གྲུབ་ཆེན ༠༤་འཇིགས་མེད་ཕྲིན་ལས་དཔལ་འབར།
statistics:
  ocr_word_mean_confidence_index: 0.9531052476864013
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I8LS18300:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS18300
      total_pages: 54
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I8LS18300.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9531052476864013
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
