id: P001749
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18279
  title: དྲི་བ་དབྱུག་གུས་བསྣུན་པར་རྔ་རྒན་ཧྲིལ་པོའི་སྒྲ་དབྱངས་བློ་གསལ་རྣ་རྒྱན།
  author: ''
  volumes:
    bdcc05bff77344d395b6d0393e2128b4:
      image_group_id: I8LS18300
      title: ''
      volume_number: 1
      total_pages: 54
      base_file: v001.txt
