id: P001749
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 10:18:31.794348
source_metadata:
  id: bdr:W8LS18279
  title: དྲི་བ་དབྱུག་གུས་བསྣུན་པར་རྔ་རྒན་ཧྲིལ་པོའི་སྒྲ་དབྱངས་བློ་གསལ་རྣ་རྒྱན།
  author: ''
  volumes:
    bdcc05bff77344d395b6d0393e2128b4:
      image_group_id: I8LS18300
      title: ''
      volume_number: 1
      total_pages: 54
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
